### ISSUE TITLE
Server stops accepting requests

### ISSUE THREAD

**Issue by mfaheemakhtar** [alykoshin/express-queue#4]
The module is not working for me very well.

Once the queue is empty, the server does not accept any request and I have to restart the process again.

I'm using "request" module to upload a file, compress using imagemin mozjpeg and then save to disk.

Any idea?

Please note that I'm using a for loop to send multiple request at once. 

My queue limit is 2, for testing.

I'm using Windows 8.1, Node 8.9.1

**Comment by alykoshin** [comment]
This library is know to work with the provided example and some of my apps.
If you can reduce your code to something quite small with reproducible behavior then it will be easy to trace to the roots of the problem.

**Comment by mfaheemakhtar** [comment]
Slightly busy but will try share the code within few days.
