### ISSUE TITLE
No  response on exceeding queuedLimit

### ISSUE THREAD

**Issue by robertmagier** [alykoshin/express-queue#6]
Module is hanging when more jobs than specified are added to the queue. This is because there is no event listener for 'reject'  like there is for 'process'

```
  self.jobQueue.on('reject', function(job) {
    console.log('Job rejected')
    job.data.res.status(200).end()
  });
```

It is already fixed in PR #5

**Comment by alykoshin** [comment]
Merged, published as v0.0.13
